name: Send Daily Email

on:
  schedule:
    - cron: '45 12 * * *'  # This is 6:00 PM IST
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run script
      env:
        EMAIL_USER: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASS: ${{ secrets.SENDER_PASSWORD }}
      run: python reminder.py

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit changes
      run: |
        git add current_index.txt
        git commit -m "Update current index" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
