name: Send Daily Email

on:
  schedule:
    - cron: '25 11 * * *'  # Runs at 9 AM UTC every day

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install smtplib
    
    - name: Run script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      run: python send_email.py
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add current_index.txt
        git commit -m "Update current index" || echo "No changes to commit"
        git push