name: Send Daily Email

on:
  schedule:
    - cron: '36 19 */2 * *'  # This is 6:00 PM IST
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install any additional dependencies your script needs
        # Example: pip install -r requirements.txt

    - name: Run script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        EMAIL1: ${{ secrets.EMAIL1 }}
        EMAIL2: ${{ secrets.EMAIL2 }}
        EMAIL3: ${{ secrets.EMAIL3 }}
      run: python reminder.py

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit changes
      run: |
        git add current_index.txt
        git commit -m "Update current index" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
